# Generated by Django 5.0.6 on 2024-06-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion'),
        ),
    ]
